_1db.get and 1dbget created

diff --git a/nh1 b/nh1
--- a/nh1
+++ b/nh1
@@ -12,7 +12,7 @@
 shopt -s expand_aliases
 
 # Global variables
-_1VERSION=1.0n14
+_1VERSION=1.0n15
 
 _1MODULES=(app audio backup canva misc network rpg)
 
@@ -337,7 +337,7 @@ _nh1customvars() {
 	unset -f 1help 1tint _1sudo 1check 1bashrc 1refresh 1update 1version 
 	unset -f 1clean 1help _1compl _1list 1translate _nh1complete _nh1init
 	unset -f _nh1customvars 1info _1modrun 1verbose _1menuitem _1verb
-	unset -f 1builddoc 1db 1dbget 1dbset _1db
+	unset -f 1builddoc 1db 1dbget 1dbset _1db _1db.get
 }
 
 # @description Menu for NH1.
@@ -553,7 +553,7 @@ _nh1customvars() {
 # @exitcode 2 File not exists
 # @exitcode 3 Wrong usage
 _1db() {
-	local DBPATH DBEXT
+	local DBPATH DBEXT OPER DBNAME
 	DBPATH="$1"
 	DBEXT="$2"
 	OPER="$3"
@@ -588,6 +588,42 @@ _1db() {
 	return 3
 }
 
+# @description Get value for some saved variable
+# @arg $1 string Path for database
+# @arg $2 string File extension
+# @arg $3 string Database name
+# @arg $4 string Variable name
+# @exitcode 0 Ok
+# @exitcode 1 Var not found
+# @exitcode 2 File not found
+# @exitcode 3 Wrong usage
+_1db.get() {
+	local DBPATH DBEXT DBNAME VARNAME LIN
+	DBPATH="$1"
+	DBEXT="$2"
+	DBNAME="$3"
+	VARNAME="$4"
+	if [ $# -eq 4 ]
+	then
+		if [ -f "$DBPATH/$DBNAME.$DBEXT" ]
+		then
+			LIN=$(grep "^$VARNAME=" "$DBPATH/$DBNAME.$DBEXT")
+			if [ $? -eq 0 ]
+			then
+				echo "$LIN" | sed "s/$VARNAME=\(.*\)/\1/"
+				return 0
+			else
+				_1verb "$(printf "$(_1text "Variable %s not found in database %s.")\n" "$VARNAME" "$DBNAME")"
+				return 1
+			fi
+		else
+			_1verb "$(printf "$(_1text "Database %s not found.")\n" "$DBNAME")"
+			return 2
+		fi
+	fi
+	return 3
+}
+
 # @description List or manage a internal key-value database
 # @arg $1 string Command: new or del (optional).
 # @arg $2 string Database name (optional)
@@ -606,6 +642,21 @@ _1db() {
 		printf "1db - %s\n" "$(_1text "list all databases.")"
 		printf "1db new [%s] - %s\n" "$(_1text "name")" "$(_1text "creates a new database.")"
 		printf "1db del [%s] - %s\n" "$(_1text "name")" "$(_1text "removes the database.")"
+		return 0
+	fi
+}
+
+# @description Get a value from internal key-valeu database
+# @arg $1 string Database name
+# @arg $2 string Variable name
+1dbget() {
+	if [ $# -eq 2 ]
+	then
+		_1db.get "$_1DBDIR" "1db" "$1" "$2"
+		return $?
+	else
+		_1text "Usage: "
+		printf "1dbget [%s] [%s]\n" "$(_1text "database name")" "$(_1text "variable name")"
 		return 0
 	fi
 }
